{
    'name': 'Dashboard Analytics',
    'version': '1.0',
    'summary': 'Module de statistiques et analytics',
    'description': 'Dashboard pour visualiser les statistiques',
    'author': 'Ton Nom',
    'category': 'Reporting',
    'depends': ['base', 'web', 'reservation'],
    'data': [
        'views/dashboard_statistiques_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dashboard_analytics/static/src/js/dashboard_statistiques.js',
            'dashboard_analytics/static/src/js/Panier_moyen.js',
            'dashboard_analytics/static/src/js/balance_dashboard.js',
            'dashboard_analytics/static/src/js/reservation_dashboard.js',
            'dashboard_analytics/static/src/js/depense_dashboard.js',
            'dashboard_analytics/static/src/js/ca_dashboard.js',
            'dashboard_analytics/static/src/js/Tresorerie_dashboard.js',
            'dashboard_analytics/static/src/js/Taux_remplissage.js',
            'dashboard_analytics/static/src/css/dashboard_statistiques.css',
            'dashboard_analytics/static/src/xml/dashboard_statistiques.xml',
            'dashboard_analytics/static/src/xml/balance_dashboard.xml',
            'dashboard_analytics/static/src/xml/Taux_remplissage.xml',
            'dashboard_analytics/static/src/xml/Panier_moyen.xml',
            'dashboard_analytics/static/src/xml/depense_dashboard.xml',
            'dashboard_analytics/static/src/xml/ca_dashboard.xml',
            'dashboard_analytics/static/src/xml/Tresorerie_dashboard.xml',
            'dashboard_analytics/static/src/xml/reservation_dashboard.xml',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
}